### PR TITLE
add test

### PR DESCRIPTION
**Pull request by alisterburt**
this PR adds a test for the behaviour added in napari/napari#4267

I can't reproduce the failure locally but this should cover it :)

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
@alisterburt Is there a way for me to run this test locally without the patch? Can I copy-pasta into a .py and do something like `pytest test.py`? 
Because if I understand correctly, when I merge then the fix and the test will be together, so will it be testing anything?

**Comment by alisterburt** [comment]
You're right yes 🙂 you could do what you suggested yes, or copy and paste the test into your branch and temporarily roll back/comment out your changes

**Comment by psobolewskiPhD** [comment]
Ok, it was easier to copy-pasta (sensing a trend?) the imports of the test_shapes.py along with your test. Here's results for napari with this branch (issue fixed):
```
╰─ pytest shape_thumb_test.py                                    (apple-TF28) ─╯
============================= test session starts ==============================
platform darwin -- Python 3.9.10, pytest-7.0.1, pluggy-1.0.0
PyQt5 5.15.4 -- Qt runtime 5.15.2 -- Qt compiled 5.15.2
rootdir: /Users/piotrsobolewski/Dev
plugins: qt-4.0.2, napari-plugin-engine-0.2.0, napari-0.4.16.dev18+g86222aaa.d20220315
collected 1 item                                                               

shape_thumb_test.py .                                                    [100%]

=============================== warnings summary ===============================
shape_thumb_test.py::test_update_thumbnail_empty_shapes
  /Users/piotrsobolewski/Dev/miniforge3/envs/apple-TF28/lib/python3.9/site-packages/numpy/core/numeric.py:2446: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
    return bool(asarray(a1 == a2).all())

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 1 passed, 1 warning in 0.49s =========================
``` 
And here is Live (0.4.15):
```
╰─ pytest shape_thumb_test.py                                     (napari-CL) ─╯
============================= test session starts ==============================
platform darwin -- Python 3.9.10, pytest-7.1.0, pluggy-1.0.0
rootdir: /Users/piotrsobolewski/Dev
plugins: napari-plugin-engine-0.2.0, napari-0.4.15
collected 1 item                                                               

shape_thumb_test.py .                                                    [100%]

=============================== warnings summary ===============================
shape_thumb_test.py::test_update_thumbnail_empty_shapes
  /Users/piotrsobolewski/Dev/miniforge3/envs/napari-CL/lib/python3.9/site-packages/numpy/core/numeric.py:2449: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
    return bool(asarray(a1 == a2).all())

shape_thumb_test.py::test_update_thumbnail_empty_shapes
shape_thumb_test.py::test_update_thumbnail_empty_shapes
  /Users/piotrsobolewski/Dev/miniforge3/envs/napari-CL/lib/python3.9/site-packages/napari/layers/shapes/shapes.py:2548: RuntimeWarning: divide by zero encountered in true_divide
    zoom_factor = np.divide(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================== 1 passed, 3 warnings in 0.69s =========================
```
The test passes but there is the warning about divide-by-zero, same error as the issue.

**Comment by alisterburt** [comment]
git is more fun with friends! 🥳 

absolutely - if you're happy with the changes then merge away

**Comment by alisterburt** [comment]
For clarity: I have made a PR to your branch directly. The same branch is the one you are proposing to napari so yes, these changes will be reflected in your PR

**Comment by alisterburt** [comment]
Missed the details about the test - if it raises the warning that's great, it will at least pop up that way when the test suite runs :)

**Comment by psobolewskiPhD** [comment]
Thanks for your patience.

**Pull request merged**
